#lang typed/racket

(require graph-executor/prompt)
(require "../llm/llm.rkt")

(provide llm-prompt)

(: llm-prompt (All (A)
                   (case-> (->* (String (List 'const
                                              (-> Any Boolean : #:+ A)
                                              (∩ A Prompt-Value)))
                                (Role)
                                (∩ A Prompt-Value))
                           (->* (String (List 'choose
                                              (-> Any Boolean : #:+ A)
                                              (Listof (U (∩ A String)
                                                         (List (∩ A String) String)))))
                                (Role)
                                (∩ String A))
                           (->* (String (List 'string))
                                (Role)
                                String)
                           (->* (String (List 'integer))
                                (Role)
                                Integer)
                           (->* (String (List 'natural))
                                (Role)
                                Natural)
                           (->* (String (List 'positive))
                                (Role)
                                Positive-Integer)
                           (->* (String (List 'range 'from Natural 'to Natural))
                                (Role)
                                Natural)
                           (->* (String (List 'range 'from Integer 'to Integer))
                                (Role)
                                Integer)
                           (->* (String (List 'random Positive-Integer))
                                (Role)
                                Natural))))
(define (llm-prompt title op [role (current-default-llm-role)])
  ((inst prompt A) title op (hash 'llm-role role)))
